### ISSUE TITLE
move the tests and their contents to their own folder

### ISSUE THREAD

**Issue by aspriddell** [dragonfruitnetwork/dragon6-api#108]
Move anything that references a test - including the demo program - to a folder called `tests` or similar

**Comment by Druffl3** [comment]
Hey, should it be moved to this folder: /DragonFruit.Six.API.Tests/Tests ?

**Comment by aspriddell** [comment]
no - was planning on moving the `DragonFruit.Six.API.Tests`, `DragonFruit.Six.API.Tests.Common` and `DragonFruit.Six.API.Demo` to a folder called `tests` in the same dir. The CI and solution file will need updating too, if you want to have a go.

**Comment by aspriddell** [comment]
@Druffl3 you planning on taking this on?

**Comment by Druffl3** [comment]
Yes, sorry for the late response.

**Comment by Druffl3** [comment]
Have submitted a PR here #168

**Comment by Druffl3** [comment]
`refusing to allow an OAuth App to create or update workflow `.github/workflows/tests.yaml` without `workflow` scope`

If I try to update the yaml file to take Demo project from "Tests" directory:
```
  - name: Demo App
        run: |
          cd Tests/DragonFruit.Six.API.Demo
          dotnet run
```
