### ISSUE TITLE
convert reference dictionaries to functions

### ISSUE THREAD

**Issue by aspriddell** [dragonfruitnetwork/Dragon6-API#110]
The dictionaries could probably be converted to a lookup function instead of a static variable (a switch maybe?)

https://github.com/dragonfruitnetwork/Dragon6-API/blob/66d4dc7c66e99fe8f326260c1322ccb25cb32deb/DragonFruit.Six.API/References.cs#L15-L96

**Comment by abuZayed15** [comment]
Hi, Can I take this issue and give it a shot? I learning more about C# and your repo looks interesting.

**Comment by aspriddell** [comment]
@abuZayed15 of course! Probably looking at a `switch` statement (the one with the arms like `1 => new RankContainer(),` with 0 and unknown as `_` at the bottom.

If you need any help or assistance feel free to open an issue or use our [discord server](https://dragon6.dragonfruit.network/discord)

**Comment by abuZayed15** [comment]
@aspriddell Thank you! I joined the Discord Server as ceterisParibus19 so I will ask you more questions there. 

Thank you for letting to work on this issue!
