### ISSUE TITLE
Split PvP and PvE stats into 2 separate requests

### ISSUE THREAD

**Issue by aspriddell** [dragonfruitnetwork/dragon6-api#135]
While it _is_ a breaking change, it's a good idea because in most cases we don't need all the stats.

**Comment by byBlurr** [comment]
Was this not done yet? Is it StatsRequest.cs that you want to be split into separate requests?

How would you like it to be separated? Keep 'StatsRequest' as casual and add 'RankedStatsRequest' for the ranked stats?

**Comment by aspriddell** [comment]
well, basically the only thing that actually changes is the keys, for example https://github.com/dragonfruitnetwork/dragon6-api/blob/f0050b108dd70b4f6f29beb5479882ad9344fe83/DragonFruit.Six.API/Data/Strings/Weapon.cs#L8 `pvp` gets changed to `pve` and the same would need to be applied to the deserializer. as far as i'm concerned, it's not really worth doing unless somebody really wants terrorist hunt stats

**Comment by byBlurr** [comment]
Just now realised I misread the title, that's my bad...

So as of right now its only PvP stats (which makes sense) so this would be just making the PvE stats available? Taking weapon stats as an example... Add the PvE strings to Data/Strings/Weapons.cs and then create WeaponStatsDeserializer, WeaponStats and WeaponStatsRequest for PvE. Keeping them entirely separate (Except the strings). Then finally bringing it together with a GetPveWeaponStats() in WeaponStatsExtensions.cs

Am I getting this right? If not let me know what I am missing or if I have got it all wrong 😂

**Comment by aspriddell** [comment]
in dragon6 (app) it uses this:
![image](https://user-images.githubusercontent.com/10289119/106128051-fcb90e00-6156-11eb-9852-da9cfca72f69.png)

so there are already some `pve` strings there, but as i've discovered a lot of them are looking like they work both ways.
Not too sure if there's a best-case here, as we can get away with a single request right now, but it could end up splitting into two requests with 2 sets of very similar responses

**Comment by byBlurr** [comment]
I believe the way I said before prevents it from being breaking and would be less work, as like you said its terrorist hunt. I feel no bad can come from it, as it makes more data available. Then at a later date, it could be reworked to be more like above

**Comment by aspriddell** [comment]
> I believe the way I said before prevents it from being breaking and would be less work, as like you said its terrorist hunt. I feel no bad can come from it, as it makes more data available. Then at a later date, it could be reworked to be more like above

as the stats and formats for this are now set in stone, i don't see why not

**Comment by byBlurr** [comment]
Which stats are relevant here? Weapons and Operator? General stats already have training right?

**Comment by aspriddell** [comment]
think so

**Comment by byBlurr** [comment]
Ok, once I have done the namespaces refactor, I will assign myself to this issue. Looks like its the Weapons and Operator stats

**Comment by byBlurr** [comment]
How would you prefer them to be named? Personally I think PickedTraining @aspriddell 

![image](https://user-images.githubusercontent.com/20552533/106148121-9214cc00-6170-11eb-8624-c64cb4084728.png)

**Comment by aspriddell** [comment]
top one makes more sense imo
