### ISSUE TITLE
Make some stats null

### ISSUE THREAD

**Issue by aspriddell** [dragonfruitnetwork/Dragon6-API#137]
If the server doesn't provide some stats (i.e if a user has never played siege) do we want to keep the system that swaps in a default value or just use a cast to a null value?

(cc @byBlurr and whoever uses this library)

**Comment by byBlurr** [comment]
I personally always do null checks anyway but either way doesnt make a difference because they can just as easily check if the players played 0 games etc.

**Comment by aspriddell** [comment]
good point, probably best to leave as-is considering the heavier computational calculations are done once on demand and stored (thanks to the new `RatioUtils` class)
