### ISSUE TITLE
update file structure

### ISSUE THREAD

**Issue by aspriddell** [dragonfruitnetwork/dragon6-api#208]
needs to apply to dragon6 modern stats api as well.

change the api source dir to `src` and the tests directory to `tests` and the resources can then house the nuget package.

**Comment by byBlurr** [comment]
Do you mean the project folders here? so 'DragonFruit.Six.API' and 'DragonFruit.Six.API.Tests'? If so couldn't this be moved into #209 / #210 ?

**Comment by aspriddell** [comment]
well yeah, but it's a little late (i already went and renamed them all manually)

**Comment by byBlurr** [comment]
Are we good to close this issue then or would you like to do it in the future?

**Comment by aspriddell** [comment]
would be nice for the future - so i suppose we should keep this open. I'll probably do this one anyways though

**Comment by byBlurr** [comment]
Do you plan on doing this for the first 2021 update or later on?

**Comment by aspriddell** [comment]
probably target it for later on
