### ISSUE TITLE
refactor namespaces

### ISSUE THREAD

**Issue by aspriddell** [dragonfruitnetwork/dragon6-api#209]
Personally, i don't like the api namespace being in capitals. It looks better in `Title Case`.

**Comment by byBlurr** [comment]
DragonFruit.Six.API.Data.Containers -> DragonFruit.Six.Api.Data.Containers?

**Comment by aspriddell** [comment]
yeah - just to make it look more universal. if you think it would be better as is then it can stay.

**Comment by byBlurr** [comment]
Personally, I think Api would be better than API.

(Just a suggestion as namespaces are being changed, might as well make sure we don't want to change them again)

I feel some of the namespaces are too long (Maybe that's just me though). An example is the Data namespace required here?
`DragonFruit.Six.API.Data.Requests -> DragonFruit.Six.Api.Requests`. Or would this then cause problems with classes such as WeaponStats.cs? They could keep the Data namespace but that would maybe make it inconsistent?

**Comment by aspriddell** [comment]
if we're going to do a mass refactor, I think having it as the first 2021 release will make it fine to break everything.

my opinion:

- move `verification` and `developer` to `services`, so `services.verification` and `services.developer` (or if there's a better term for developer then change that)
- move all`WeaponStats`, `SeasonalStats`, etc. to Entities
- move everything out of data and drop it entirely

^ that would probably make it so much easier to work with, right?

**Comment by byBlurr** [comment]
Yes, I think that would make it easier to work with. Are there any other changes being made currently that need to be merged first?

**Comment by aspriddell** [comment]
no, I moved my efforts to Orbit and the modern stats api. feel free to pr if you want to.

**Comment by byBlurr** [comment]
Would you prefer the Entities, Containers etc folders inside the Data folder but not include .Data in the namespace? Or move them all out of the Data folder. The Data namespace is already removed, just thinking of keeping it tidy for us to work on.
![image](https://user-images.githubusercontent.com/20552533/106141163-a56f6980-6167-11eb-8ed8-c79611c224d2.png)

**Comment by aspriddell** [comment]
I'm pretty sure the folders need to map to the namespace otherwise resharper will complain.

i think it would be better to drop `.Data` altogether (as it doesn't serve any purpose). Any .cs file in the top level (the entities themselves) can go into their own folder, like `Objects` or `Entities`

**Comment by byBlurr** [comment]
![image](https://user-images.githubusercontent.com/20552533/106145482-84aa1280-616d-11eb-940c-681631f59f2f.png)

**Comment by aspriddell** [comment]
looks sooooo much better :+1:
