### ISSUE TITLE
convert all general stats deserialisers to return ILookup<string, StatsObject>

### ISSUE THREAD

**Issue by aspriddell** [dragonfruitnetwork/dragon6-api#216]
if extension signatures are changed to resemble `public static ILookup<string,  GeneralStats> DeserializeGeneralStatsFor(this JObject jObject)` and then `jObject` to `jObject[Misc.Results] as Dictionary<string, JObject>` and loop through that, allowing the Guid to be changed to whatever mentioned in #214.

Reasoning: ILookup can return null for a guid that doesn't exist and the user can then pull out the data they need based on the account and handle them without creating an enumerator each time to use `SingleOrDefault()`. We can also hide the Guid by making it internal or something...

**Comment by byBlurr** [comment]
I don't have any issues with this proposal
