### ISSUE TITLE
add debugview attributes

### ISSUE THREAD

**Issue by aspriddell** [dragonfruitnetwork/dragon6-api#222]
would be helpful in showing things like the user's profile id quickly (weapon/op stats can have the class/index too)

**Comment by Skvorecz** [comment]
Can you give an example of what you mean?

**Comment by aspriddell** [comment]
say you add a breakpoint and hover over a `GeneralStats` object, it should display the profile id and maybe some general stats for debugging. There's an attribute called `DebugView` iirc.

It's basically implementing what's mentioned at https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/enhancing-debugging-with-the-debugger-display-attributes
