### ISSUE TITLE
Legacy stats depreciation information

### ISSUE THREAD

**Issue by aspriddell** [dragonfruitnetwork/dragon6-api#296]
It has been known for some time that legacy stats have indeed been killed off by ubisoft. I've been working on a redesign of the site, and have a few things to share:

- It looks like all stats under the legacy namespace of this api have been frozen
- They were frozen at the end of Crystal Guard (season 23)
- Seasonal stats still work, and in the latest api update we added support for casual stats, so it is possible to aggregate both sources to get the current stats
- All other stats are basically dead and should only be used for archival purposes. I'm going to add obsoletion notices to all of them, but won't remove them for the foreseeable future (or when ubisoft close that whole system down)

In #308, a method was added to `LegacyPlaylistStats` to allow kills, deaths, wins and losses to be applied from a `SeasonalStats` object to ease updating stats.

**Comment by CNDRD** [comment]
Hey there,

I have basically no experience with C#, but I did just rewrite my Python Siege API library ([siegeapi](https://github.com/CNDRD/siegeapi)) to ditch the old frozen stats and added in the new ones
So if you wanna know anything about the new endpoints, I'm happy to share 😃

**Comment by aspriddell** [comment]
Cheers @CNDRD, most of the modern stats have been added in #280, just need to add the deathmatch board `pvp_warmup`, newcomer playlist and add a note about skill records not returning the most recent season.

I'll take a look at your python api and see if there's anything else I've missed.

**Comment by aspriddell** [comment]
closing as all guidance should be accurate and all planned features have been added (and are in a stable build)
