### ISSUE TITLE
Cross-platform stats updates

### ISSUE THREAD

**Issue by aspriddell** [dragonfruitnetwork/dragon6-api#338]
As of 6th December, all stats collected by the "modern" stats service will now be split into platform groups to allow cross-save and cross-progression.

To-do:

- [x] Add `PlatformGroup` enum and `ModernStatsRequest` property
- [x] Add seasons option to `ModernStatsRequest`
- [ ] Add exceptions when setting two conflicting properties in a ModernStatsRequest
  - Setting a Start/End date and specifying a list of seasons
  - Setting a `PlatformGroup` and a `Platform`

**Comment by SwiftCODA** [comment]
> As of 6th December, all stats collected by the "modern" stats service will now be split into platform groups to allow cross-save and cross-progression.
> 
> To-do:
> 
> * [x]  Add `PlatformGroup` enum and `ModernStatsRequest` property
> * [x]  Add seasons option to `ModernStatsRequest`
> * [ ]  Add exceptions when setting two conflicting properties in a ModernStatsRequest
>   
>   * Setting a Start/End date and specifying a list of seasons
>   * Setting a `PlatformGroup` and a `Platform`

Please weigh in here:
https://github.com/Seems2Legit/Rainbow-Six-Siege-Player-Stats-API/issues/91#issue-1485588198
