### ISSUE TITLE
add auto-publish script

### ISSUE THREAD

**Issue by aspriddell** [dragonfruitnetwork/Dragon6-API#48]
extend travis to, once tested and all passing, auto pack the nuget package and push it. Will need to be done on a windows machine as we already have a (now) working push script [here](https://github.com/dragonfruitnetwork/Dragon6-Locale/blob/master/Deploy.ps1)

**Comment by byBlurr** [comment]
Could this publish 'beta' versions and then have official release versions manually published for more consistency with releases?

**Comment by aspriddell** [comment]
sounds like a good idea, maybe split into two branches: beta and master. Or even master (for beta) and production?

**Comment by byBlurr** [comment]
Yeah using separated branches would work well
