### ISSUE TITLE
General Stats Containers

### ISSUE THREAD

**Issue by byBlurr** [dragonfruitnetwork/Dragon6-API#53]
To make the api more user friendly, we will benefit from creating containers for the general stats. This will reduce the amount of clutter within the GeneralStats.

Within the general stats, we will have RankedStatsContainer, CasualStatsContainer and TrainingStatsContainer.

**Comment by aspriddell** [comment]
@byBlurr does this look like what you imagined?

![image](https://user-images.githubusercontent.com/10289119/76830304-e2b35d00-681c-11ea-8531-81740b294a0a.png)

**Comment by byBlurr** [comment]
Yes, that will make the api a lot more user friendly and organised!

**Comment by aspriddell** [comment]
also made containers for your `Rank` class and `HighScores`

**Comment by byBlurr** [comment]
👍
