### ISSUE TITLE
can i get the source of the rainbow6 stat api?

### ISSUE THREAD

**Issue by honkkki** [dragonfruitnetwork/Dragon6-API#63]
because i want to make an app with the stat api

**Comment by aspriddell** [comment]
What do you mean by source? If you are referring to the endpoints/urls they are [here](https://github.com/dragonfruitnetwork/Dragon6-API/blob/master/DragonFruit.Six.API/Endpoints.cs)

**Comment by aspriddell** [comment]
> because i want to make an app with the stat api

What api? The r6 official or ours?

**Comment by honkkki** [comment]
> > because i want to make an app with the stat api
> 
> What api? The r6 official or ours?

r6 official. the source api which i can get data by curl

**Comment by aspriddell** [comment]
it's a little more complicated that a single url, see [this](https://github.com/dragonfruitnetwork/Dragon6-API/blob/master/DragonFruit.Six.API/Endpoints.cs) for what we use

**Comment by aspriddell** [comment]
if you want to setup your own server for the API, see [Dragon6-Server](https://github.com/dragonfruitnetwork/Dragon6-Server)

**Comment by honkkki** [comment]
> it's a little more complicated that a single url, see [this](https://github.com/dragonfruitnetwork/Dragon6-API/blob/master/DragonFruit.Six.API/Endpoints.cs) for what we use

Is there official documentation of official api?

**Comment by aspriddell** [comment]
no. no there isn't

**Comment by honkkki** [comment]
> no. no there isn't - hence this api
> 
> Are you planning on using Dragon6 to get the stats?

what should i do with using dragon6 api

**Comment by aspriddell** [comment]
if you want a json api you can deploy your own version of [Dragon6-Server](https://github.com/dragonfruitnetwork/Dragon6-Server) and then use the endpoints in your app to get the stats

**Comment by honkkki** [comment]
> If you want a json api you can deploy your own version of [Dragon6-Server](https://github.com/dragonfruitnetwork/Dragon6-Server) and then use the endpoints in your app to get the stats - you will need to modify [this](https://github.com/dragonfruitnetwork/Dragon6-Server/blob/8f5a0c36d59547992376461555606981589fdd25/DragonFruit.Six.Web/Services/StatsClient.cs#L28) to have your own set of credentials. You'll have to host your own copy of it somewhere on a server.
> 
> With regards to the app you want to make, if you plan on distributing it (i.e not a website) you will **require** a server as account login details are needed to get the stats (it doesn't matter what login, it needs to be a valid ubisoft club login though)

thank you very much!

**Comment by aspriddell** [comment]
it's fine - if you need any help don't hesitate to open another issue - we'll respond asap
